var jQuery = function(){};
jQuery.css = function(){};
jQuery.fail = function(){};
jQuery.render = function(){};
jQuery.append = function(){};
jQuery.ajax = function(){};
var $ = jQuery;
var EJS = function(){};
var Query = function(){};
Query.insert = function(any){};
Query.run = function(){};
Query.then = function(){};
var ImagesSQL = function(){};
var Users = function(){};
var Article = function(){};
Article.create = function(){};
var system = {};
system.init = function(){};
system.mkdir = function(){};
system.destpath = function(){};
var Organization = function(){};
Organization.id = function(){};
Organization.isRoot = function(){};
Organization.paretnId = function(){};
Organization.children = function(){};
var _ = function(){};
_.each = function(){};
translate();
showDanger();
createUser();
createArticle();
